version: '2.1'

volumes:
  netdatacache:
  netdatalib:
  pathfinder:

services:
  starknet-pathfinder:
    build: ./pathfinder
    ports:
      - "9545:9545"
    volumes:
      - pathfinder:/usr/share/pathfinder
    environment:
      HTTP_RPC: "0.0.0.0:9545"
      ETH_RPC_URL: "https://eth-mainnet.alchemyapi.io/v2/3QYDn_ym4Yjcx4TEtGMVKAhUQh-ZwAF3"
      PASSWORD: ""
      IDLE: 0
      LOCATION: "ON"
      LOCATION_API: "https://starknet.io/rpi-node/"
  netdata:
    build: ./netdata
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - "19999:19999"
    labels:
      - "io.balena.features.balena-socket=1"
      - "io.balena.features.procfs=1"
      - "io.balena.features.supervisor-api=1"
      - "io.balena.features.sysfs=1"
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdatav
